# Generated by Django 2.1.5 on 2019-08-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
    ]
